apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
  - name: k8s-azure-file
      hostPath:
        path: /etc/kubernetes/azure.json
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /etc/kubernetes/azure.json
      name: k8s-azure-file
      readOnly: true
